apiVersion: v1
kind: Service
metadata:
  name: veyra-backend-service
spec:
  type: NodePort
  selector:
    app: veyra-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500